// <auto-generated />
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Data.Migrations
{
    [DbContext(typeof(BrainContext))]
    [Migration("20250201191734_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("Core.Entities.BrainStormSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SessionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BrainStormSessions");
                });

            modelBuilder.Entity("Core.Entities.Storm", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BrainStormSessionId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("StormId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BrainStormSessionId");

                    b.HasIndex("StormId");

                    b.ToTable("Storms");
                });

            modelBuilder.Entity("Core.Entities.StormChild", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ChildId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParentId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("StormChildren");
                });

            modelBuilder.Entity("Core.Entities.Storm", b =>
                {
                    b.HasOne("Core.Entities.BrainStormSession", null)
                        .WithMany("Storms")
                        .HasForeignKey("BrainStormSessionId");

                    b.HasOne("Core.Entities.Storm", null)
                        .WithMany("Storms")
                        .HasForeignKey("StormId");
                });

            modelBuilder.Entity("Core.Entities.BrainStormSession", b =>
                {
                    b.Navigation("Storms");
                });

            modelBuilder.Entity("Core.Entities.Storm", b =>
                {
                    b.Navigation("Storms");
                });
#pragma warning restore 612, 618
        }
    }
}
